/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AprovacaoRouteImport } from './routes/aprovacao'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EmAndamentoRouteImport } from './routes/em-andamento'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as PesquisaRouteImport } from './routes/pesquisa'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as LicitacoesIndexRouteImport } from './routes/licitacoes.index'
import { Route as LicitacoesIdRouteImport } from './routes/licitacoes.$id'
import { Route as ApiPublicHooksMonitorarChatsRouteImport } from './routes/api/public/hooks/monitorar-chats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AprovacaoRoute = AprovacaoRouteImport.update({
  id: '/aprovacao',
  path: '/aprovacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EmAndamentoRoute = EmAndamentoRouteImport.update({
  id: '/em-andamento',
  path: '/em-andamento',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaRoute = PesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const LicitacoesIndexRoute = LicitacoesIndexRouteImport.update({
  id: '/licitacoes/',
  path: '/licitacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const LicitacoesIdRoute = LicitacoesIdRouteImport.update({
  id: '/licitacoes/$id',
  path: '/licitacoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksMonitorarChatsRoute =
  ApiPublicHooksMonitorarChatsRouteImport.update({
    id: '/api/public/hooks/monitorar-chats',
    path: '/api/public/hooks/monitorar-chats',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alertas': typeof AlertasRoute
  '/aprovacao': typeof AprovacaoRoute
  '/auth': typeof AuthRoute
  '/em-andamento': typeof EmAndamentoRoute
  '/equipe': typeof EquipeRoute
  '/pesquisa': typeof PesquisaRoute
  '/relatorios': typeof RelatoriosRoute
  '/licitacoes/$id': typeof LicitacoesIdRoute
  '/licitacoes/': typeof LicitacoesIndexRoute
  '/api/public/hooks/monitorar-chats': typeof ApiPublicHooksMonitorarChatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alertas': typeof AlertasRoute
  '/aprovacao': typeof AprovacaoRoute
  '/auth': typeof AuthRoute
  '/em-andamento': typeof EmAndamentoRoute
  '/equipe': typeof EquipeRoute
  '/pesquisa': typeof PesquisaRoute
  '/relatorios': typeof RelatoriosRoute
  '/licitacoes/$id': typeof LicitacoesIdRoute
  '/licitacoes': typeof LicitacoesIndexRoute
  '/api/public/hooks/monitorar-chats': typeof ApiPublicHooksMonitorarChatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alertas': typeof AlertasRoute
  '/aprovacao': typeof AprovacaoRoute
  '/auth': typeof AuthRoute
  '/em-andamento': typeof EmAndamentoRoute
  '/equipe': typeof EquipeRoute
  '/pesquisa': typeof PesquisaRoute
  '/relatorios': typeof RelatoriosRoute
  '/licitacoes/$id': typeof LicitacoesIdRoute
  '/licitacoes/': typeof LicitacoesIndexRoute
  '/api/public/hooks/monitorar-chats': typeof ApiPublicHooksMonitorarChatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/alertas'
    | '/aprovacao'
    | '/auth'
    | '/em-andamento'
    | '/equipe'
    | '/pesquisa'
    | '/relatorios'
    | '/licitacoes/$id'
    | '/licitacoes/'
    | '/api/public/hooks/monitorar-chats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/alertas'
    | '/aprovacao'
    | '/auth'
    | '/em-andamento'
    | '/equipe'
    | '/pesquisa'
    | '/relatorios'
    | '/licitacoes/$id'
    | '/licitacoes'
    | '/api/public/hooks/monitorar-chats'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/alertas'
    | '/aprovacao'
    | '/auth'
    | '/em-andamento'
    | '/equipe'
    | '/pesquisa'
    | '/relatorios'
    | '/licitacoes/$id'
    | '/licitacoes/'
    | '/api/public/hooks/monitorar-chats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AlertasRoute: typeof AlertasRoute
  AprovacaoRoute: typeof AprovacaoRoute
  AuthRoute: typeof AuthRoute
  EmAndamentoRoute: typeof EmAndamentoRoute
  EquipeRoute: typeof EquipeRoute
  PesquisaRoute: typeof PesquisaRoute
  RelatoriosRoute: typeof RelatoriosRoute
  LicitacoesIdRoute: typeof LicitacoesIdRoute
  LicitacoesIndexRoute: typeof LicitacoesIndexRoute
  ApiPublicHooksMonitorarChatsRoute: typeof ApiPublicHooksMonitorarChatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprovacao': {
      id: '/aprovacao'
      path: '/aprovacao'
      fullPath: '/aprovacao'
      preLoaderRoute: typeof AprovacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/em-andamento': {
      id: '/em-andamento'
      path: '/em-andamento'
      fullPath: '/em-andamento'
      preLoaderRoute: typeof EmAndamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa': {
      id: '/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof PesquisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licitacoes/': {
      id: '/licitacoes/'
      path: '/licitacoes'
      fullPath: '/licitacoes/'
      preLoaderRoute: typeof LicitacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licitacoes/$id': {
      id: '/licitacoes/$id'
      path: '/licitacoes/$id'
      fullPath: '/licitacoes/$id'
      preLoaderRoute: typeof LicitacoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/monitorar-chats': {
      id: '/api/public/hooks/monitorar-chats'
      path: '/api/public/hooks/monitorar-chats'
      fullPath: '/api/public/hooks/monitorar-chats'
      preLoaderRoute: typeof ApiPublicHooksMonitorarChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AlertasRoute: AlertasRoute,
  AprovacaoRoute: AprovacaoRoute,
  AuthRoute: AuthRoute,
  EmAndamentoRoute: EmAndamentoRoute,
  EquipeRoute: EquipeRoute,
  PesquisaRoute: PesquisaRoute,
  RelatoriosRoute: RelatoriosRoute,
  LicitacoesIdRoute: LicitacoesIdRoute,
  LicitacoesIndexRoute: LicitacoesIndexRoute,
  ApiPublicHooksMonitorarChatsRoute: ApiPublicHooksMonitorarChatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
