/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BoletinsRouteImport } from './routes/boletins'
import { Route as ChatsRouteImport } from './routes/chats'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as PesquisaRouteImport } from './routes/pesquisa'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as LicitacoesIndexRouteImport } from './routes/licitacoes.index'
import { Route as LicitacoesIdRouteImport } from './routes/licitacoes.$id'
import { Route as ApiPublicChatIngestRouteImport } from './routes/api/public/chat-ingest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BoletinsRoute = BoletinsRouteImport.update({
  id: '/boletins',
  path: '/boletins',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatsRoute = ChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaRoute = PesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const LicitacoesIndexRoute = LicitacoesIndexRouteImport.update({
  id: '/licitacoes/',
  path: '/licitacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const LicitacoesIdRoute = LicitacoesIdRouteImport.update({
  id: '/licitacoes/$id',
  path: '/licitacoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatIngestRoute = ApiPublicChatIngestRouteImport.update({
  id: '/api/public/chat-ingest',
  path: '/api/public/chat-ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alertas': typeof AlertasRoute
  '/auth': typeof AuthRoute
  '/boletins': typeof BoletinsRoute
  '/chats': typeof ChatsRoute
  '/equipe': typeof EquipeRoute
  '/pesquisa': typeof PesquisaRoute
  '/relatorios': typeof RelatoriosRoute
  '/licitacoes/$id': typeof LicitacoesIdRoute
  '/licitacoes/': typeof LicitacoesIndexRoute
  '/api/public/chat-ingest': typeof ApiPublicChatIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alertas': typeof AlertasRoute
  '/auth': typeof AuthRoute
  '/boletins': typeof BoletinsRoute
  '/chats': typeof ChatsRoute
  '/equipe': typeof EquipeRoute
  '/pesquisa': typeof PesquisaRoute
  '/relatorios': typeof RelatoriosRoute
  '/licitacoes/$id': typeof LicitacoesIdRoute
  '/licitacoes': typeof LicitacoesIndexRoute
  '/api/public/chat-ingest': typeof ApiPublicChatIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alertas': typeof AlertasRoute
  '/auth': typeof AuthRoute
  '/boletins': typeof BoletinsRoute
  '/chats': typeof ChatsRoute
  '/equipe': typeof EquipeRoute
  '/pesquisa': typeof PesquisaRoute
  '/relatorios': typeof RelatoriosRoute
  '/licitacoes/$id': typeof LicitacoesIdRoute
  '/licitacoes/': typeof LicitacoesIndexRoute
  '/api/public/chat-ingest': typeof ApiPublicChatIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/alertas'
    | '/auth'
    | '/boletins'
    | '/chats'
    | '/equipe'
    | '/pesquisa'
    | '/relatorios'
    | '/licitacoes/$id'
    | '/licitacoes/'
    | '/api/public/chat-ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/alertas'
    | '/auth'
    | '/boletins'
    | '/chats'
    | '/equipe'
    | '/pesquisa'
    | '/relatorios'
    | '/licitacoes/$id'
    | '/licitacoes'
    | '/api/public/chat-ingest'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/alertas'
    | '/auth'
    | '/boletins'
    | '/chats'
    | '/equipe'
    | '/pesquisa'
    | '/relatorios'
    | '/licitacoes/$id'
    | '/licitacoes/'
    | '/api/public/chat-ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AlertasRoute: typeof AlertasRoute
  AuthRoute: typeof AuthRoute
  BoletinsRoute: typeof BoletinsRoute
  ChatsRoute: typeof ChatsRoute
  EquipeRoute: typeof EquipeRoute
  PesquisaRoute: typeof PesquisaRoute
  RelatoriosRoute: typeof RelatoriosRoute
  LicitacoesIdRoute: typeof LicitacoesIdRoute
  LicitacoesIndexRoute: typeof LicitacoesIndexRoute
  ApiPublicChatIngestRoute: typeof ApiPublicChatIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boletins': {
      id: '/boletins'
      path: '/boletins'
      fullPath: '/boletins'
      preLoaderRoute: typeof BoletinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chats': {
      id: '/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof ChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa': {
      id: '/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof PesquisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licitacoes/': {
      id: '/licitacoes/'
      path: '/licitacoes'
      fullPath: '/licitacoes/'
      preLoaderRoute: typeof LicitacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licitacoes/$id': {
      id: '/licitacoes/$id'
      path: '/licitacoes/$id'
      fullPath: '/licitacoes/$id'
      preLoaderRoute: typeof LicitacoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat-ingest': {
      id: '/api/public/chat-ingest'
      path: '/api/public/chat-ingest'
      fullPath: '/api/public/chat-ingest'
      preLoaderRoute: typeof ApiPublicChatIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AlertasRoute: AlertasRoute,
  AuthRoute: AuthRoute,
  BoletinsRoute: BoletinsRoute,
  ChatsRoute: ChatsRoute,
  EquipeRoute: EquipeRoute,
  PesquisaRoute: PesquisaRoute,
  RelatoriosRoute: RelatoriosRoute,
  LicitacoesIdRoute: LicitacoesIdRoute,
  LicitacoesIndexRoute: LicitacoesIndexRoute,
  ApiPublicChatIngestRoute: ApiPublicChatIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
